main:
  download_repository: "https://github.com/Dyrutter/rental_prices#download" 
  #src_repository: "https://github.com/udacity/build-ml-pipeline-for-short-term-rental-prices#src" 
  project_name: rental_prices
  experiment_name: development
  execute_steps:
    - download
    - test_raw_data
    - basic_cleaning 
    - check_data
    - engineer
    - segregate
    - random_forest
    - test_regression_model
    #- EDA
  random_seed: 42
data:
  file_url: "https://github.com/Dyrutter/rental_prices/blob/main/data/sample1.csv?raw=True" # Path to data file
  reference_dataset: "rental_prices/preprocessed_data.csv:latest"
  raw_data_name: "raw_data.csv"
  raw_data_type: "raw_data"
  raw_data_description: "Raw file as downloaded"
  raw_data_artifact: "raw_data.csv:latest"
  preprocessed_data: "preprocessed_data.csv"
  engineered_data: "engineered_data.csv"
  engineer_artifact_type: "engineered_data"
  preprocessed_data_latest: "preprocessed_data.csv:latest"
  engineer_input_artifact: "data_train.csv:latest"
  engineer_output_artifact: "engineered_data.csv:latest"
  save_clean_locally: True
  save_split_locally: True
  save_engineered_locally: True
  split_artifact_root: "data"
  tfidf_max_features: 10
  sample: "sample1.csv" 
  eda_sample: "sample1.csv"
  train_data: "data_train.csv:latest" # Output of segregate step
  test_data: "data_test.csv:latest" # Output of segregate step
  kl_threshold: 0.05
  test_size: 0.2
  val_size: 0.3
  stratify_by: null
  stratify: null
  min_date: 0
  max_date: 3475 #50 is 85th percentile, 3475 is max
  min_price: 0 #10 is minimum, 40 is 5th%
  max_price: 350 #1000 is max, 350 is 95th%
  min_nights: 0
  max_nights: 1250 # Highest is 1250
  min_listings: 1
  max_listings: 330 # 95th is 14, but there are several values at 327
random_forest_pipeline:
  random_forest:
    n_estimators: 100
    criterion: 'absolute_error'
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    min_weight_fraction_leaf: 0.0
    max_features: 0.5 #'sqrt'
    max_leaf_nodes: null
    bootstrap: true
    oob_score: true
    n_jobs: -1
    random_state: 42
    verbose: 0
    warm_start: false
    ccp_alpha: 0.0
    max_samples: null
  max_tfidf_features: 10
  save_model_locally: True # added this
  output_artifact: "model_export"
  export_artifact: "model_export"
